<a href="https://colab.research.google.com/github/svetlanama/ai_practice/blob/dev/DZ_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль pandas

In [3]:
import numpy as np
import pandas as pd

# Інформація про дані
Зібрано дані продажу техніки в різних магазинах.
* OrderDate -- дата замовлення
* Region    -- регіон де розміщено магазин
* Manager   -- ім'я менеджера
* SalesMan  -- ім'я продавця
* Item      -- тип товару
* Units     -- кількість купленого товару
* Unit_price -- ціна за штуку
* Sale_amt   -- загальна вартість покупки

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/sales_data.csv", index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [5]:
df.head()

,OrderDate,Region,Manager,SalesMan,Item,Units,Unit_price,Sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
3,2018-02-26,Central,Timothy,David,Cell Phone,27.0,225.0,6075.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0

# Завдання 2

Перейменуйте стовпчики так, щоб назви містили літери нижнього регістру

In [12]:
df = df.rename(columns=str.lower)
df

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.00,1198.000,113810.00
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.00,500.000,25000.00
2,2018-02-09,Central,Hermann,Luis,Television,36.00,1198.000,43128.00
3,2018-02-26,Central,Timothy,David,Cell Phone,27.00,225.000,6075.00
4,2018-03-15,West,Timothy,Stephen,Television,56.00,1198.000,67088.00
5,2018-04-01,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00
6,2018-04-18,Central,Martha,Steven,Television,75.00,1198.000,89850.00
7,2018-05-05,Central,Hermann,Luis,Television,90.00,1198.000,107820.00
8,2018-05-22,West,Douglas,Michael,Television,32.00,1198.000,38336.00
9,2018-06-08,East,Martha,Alexander,Home Theater,60.00,500.000,30000.00
10,2018-06-25,Central,Hermann,Sigal,Television,90.00,1198.000,107820.00
11,2018-07-12,East,Martha,Diana,Home Theater,29.00,500.000,14500.00
12,2018-07-29,East,Douglas,Karen,Home Theater,81.00,500.000,40500.00
13,2018-08-15,East,Martha,Alexander,Television,35.00,1198.000,41930.00
14,2018-09-01,Central,Douglas,John,Desk,2.00,125.000,250.00
15,2018-09-18,East,Martha,Alexander,Video Games,16.00,58.500,936.00
16,2018-10-05,Central,Hermann,Sigal,Home Theater,28.00,500.000,14000.00
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.00,225.000,14400.00
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.00,225.000,3375.00
19,2018-11-25,Central,Hermann,Shelli,Video Games,96.00,58.500,5616.00
20,2018-12-12,Central,Douglas,John,Television,67.00,1198.000,80266.00
21,2018-12-29,East,Douglas,Karen,Video Games,74.00,58.500,4329.00
22,2019-01-15,Central,Timothy,David,Home Theater,46.00,500.000,23000.00
23,2019-02-01,Central,Douglas,John,Home Theater,87.00,500.000,43500.00
24,2019-02-18,East,Martha,Alexander,Home Theater,4.00,500.000,2000.00
25,2019-03-07,West,Timothy,Stephen,Home Theater,7.00,500.000,3500.00
26,2019-03-24,Central,Hermann,Luis,Video Games,50.00,58.500,2925.00
27,2019-04-10,Central,Martha,Steven,Television,66.00,1198.000,79068.00
28,2019-04-27,East,Martha,Diana,Cell Phone,96.00,225.000,21600.00
29,2019-05-14,Central,Timothy,David,Television,53.00,1198.000,63494.00
30,2019-05-31,Central,Timothy,David,Home Theater,80.00,500.000,40000.00
31,2019-06-17,Central,Hermann,Shelli,Desk,5.00,125.000,625.00
32,2019-07-04,East,Martha,Alexander,Video Games,62.00,58.500,3627.00
33,2019-07-21,Central,Hermann,Sigal,Video Games,55.00,58.500,3217.50
34,2019-08-07,Central,Hermann,Shelli,Video Games,42.00,58.500,2457.00
35,2019-08-24,West,Timothy,Stephen,Desk,3.00,125.000,375.00
36,2019-09-10,Central,Timothy,David,Television,7.00,1198.000,8386.00
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.00,225.000,17100.00
38,2019-10-14,West,Douglas,Michael,Home Theater,57.00,500.000,28500.00
39,2019-10-31,Central,Martha,Steven,Television,14.00,1198.000,16772.00
40,2019-11-17,Central,Hermann,Luis,Home Theater,11.00,500.000,5500.00
41,2019-12-04,Central,Hermann,Luis,Home Theater,94.00,500.000,47000.00
42,2019-12-21,Central,Martha,Steven,Home Theater,28.00,500.000,14000.00
43,NaN,NaN,NaN,NaN,NaN,278.00,1125.000,62550.00
44,NaN,NaN,NaN,NaN,NaN,34.75,140.625,7818.75

# Завдання 3
Виведіть дані про купівлі телевізорів та телефонів

In [14]:
df_tv_phone = df[(df['item'] == 'Television') | (df['item'] == 'Cell Phone')]
df_tv_phone

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
3,2018-02-26,Central,Timothy,David,Cell Phone,27.0,225.0,6075.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0
6,2018-04-18,Central,Martha,Steven,Television,75.0,1198.0,89850.0
7,2018-05-05,Central,Hermann,Luis,Television,90.0,1198.0,107820.0
8,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
10,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
13,2018-08-15,East,Martha,Alexander,Television,35.0,1198.0,41930.0
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
20,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
27,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
28,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
29,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
36,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0
39,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0

# Завдання 4
Яка загальна виручка у продавця Luis?

In [13]:
df_4 = df[df['salesman'] == 'Luis']['sale_amt'].sum()
df_4

206373.0

# Завдання 5

Скільки і якого товару було продано?

див groupby(),

In [17]:
df_by_key = df.groupby(['item'])['units'].sum()
df_by_key

item
Cell Phone      278.0
Desk             10.0
Home Theater    722.0
Television      716.0
Video Games     395.0
Name: units, dtype: float64

# Завдання 6
Перевірте чи правильно розраховано загальну вартість покупки. Виведіть ті рядки де є помилка. Виправте дані в таблиці

In [16]:
df_error=df[(df['sale_amt'] != df['units'] * df['unit_price'])]
df_error

   orderdate region manager salesman item   units  unit_price  sale_amt
43       NaN    NaN     NaN      NaN  NaN  278.00    1125.000  62550.00
44       NaN    NaN     NaN      NaN  NaN   34.75     140.625   7818.75