<a href="https://colab.research.google.com/github/svetlanama/ai_practice/blob/dev/DZ_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

[Опис даних](https://search.r-project.org/CRAN/refmans/PPtreeregViz/html/insurance.html)

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module3/data/insurance.csv")
df = df.select_dtypes('number')

In [3]:
df.head()

   age   bmi  children  expenses
0   19  27.9         0  16884.92
1   18  33.8         1   1725.55
2   28  33.0         3   4449.46
3   33  22.7         0  21984.47
4   32  28.9         0   3866.86

# Завдання 1
Виведіть основні числові характеристики та кількість пропущених значень по стовпчиках

In [7]:
df.shape

(1338, 4)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   bmi       1338 non-null   float64
 2   children  1338 non-null   int64
 3   expenses  1338 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 41.9 KB

In [5]:
df.isnull().sum()

age         0
bmi         0
children    0
expenses    0
dtype: int64

In [15]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

# Завдання 2
Розділіть дані на залежну y(`expenses`) та незалежну X ознаки. Розділіть дані на тренувальну та тестову частини

In [16]:
X = df.drop('expenses', axis=1)
y = df['expenses']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    train_size=0.8,
                                                    random_state=42)

In [17]:
X_train, y_train

(      age   bmi  children
 560    46  20.0         2
 1285   47  24.3         0
 1142   52  24.9         0
 969    39  34.3         5
 486    54  21.5         3
 ...   ...   ...       ...
 1095   18  31.4         4
 1130   39  23.9         5
 1294   58  25.2         0
 860    37  47.6         2
 1126   55  29.9         0

 [1070 rows x 3 columns],
 560      9193.84
 1285     8534.67
 1142    27117.99
 969      8596.83
 486     12475.35
           ...
 1095     4561.19
 1130     8582.30
 1294    11931.13
 860     46113.51
 1126    10214.64
 Name: expenses, Length: 1070, dtype: float64)

In [18]:
X_test, y_test

(      age   bmi  children
 764    45  25.2         2
 887    36  30.0         0
 890    64  26.9         0
 1293   46  25.7         3
 259    19  31.9         0
 ...   ...   ...       ...
 109    63  35.1         0
 575    58  27.2         0
 535    38  28.0         1
 543    54  47.4         0
 846    51  34.2         1

 [268 rows x 3 columns],
 764      9095.07
 887      5272.18
 890     29330.98
 1293     9301.89
 259     33750.29
           ...
 109     47055.53
 575     12222.90
 535      6067.13
 543     63770.43
 846      9872.70
 Name: expenses, Length: 268, dtype: float64)

# Завдання 3
Натренуйте LinearRegression та виведіть такі метрики: MAE, RMSE, R2

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

model = LinearRegression()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

y_pred

array([13310.79097626, 11794.15847363, 16943.29747396, 14261.24139628,
        8673.83564095, 16207.25649735,  5546.95026332, 20602.41866055,
        5803.7236314 , 15921.36345381, 10297.17358426, 14224.18027718,
       10679.4131425 , 19816.45265229, 20717.45424803, 18309.51336762,
       20015.02669105, 16981.02430109, 13932.79492742, 12308.03806382,
       10154.01688337, 15330.92831553,  8174.86457005, 11963.92986341,
       15942.50166403, 16665.38589565, 18788.09944056, 11630.87795212,
       14217.95058625,  7854.34371729, 14697.81222612, 17028.18316885,
       10113.2310599 ,  8833.52510962, 10150.292179  , 17040.6425507 ,
        7849.12841596, 13869.38029677, 13926.56523649, 14087.3249439 ,
       10393.09974071,  9733.09195753, 18701.44614381, 15373.95794823,
       14188.13354767, 16602.65280058, 10807.58964742,  9160.27565331,
       17025.32950072, 14611.56346007, 19849.45621301,  8184.89064202,
       17032.64525792,  6523.75419489, 17672.33971983, 16709.69109528,
        8972.88542947, 13844.37402882, 17681.3514022 , 16644.24768543,
       18352.54300031, 15954.27951031, 21031.67373318, 12582.0815844 ,
       15625.16733342,  9227.8911957 ,  9306.47552298, 15818.45439417,
        7434.71018593, 11864.13564923, 15160.80824419, 15893.31401709,
       15540.61449254, 14348.22754704, 16817.81545626, 11760.89373557,
       12362.70218944, 14778.30750861, 12153.0876891 , 14040.5147577 ,
        9360.26861236, 16435.31472068, 11971.5226255 , 12280.24980443,
       16785.21642623, 15483.0966988 , 12692.23472457, 16919.37727229,
       14698.89829239, 19432.18431486, 21354.29504181, 15645.97268962,
       13488.2268048 , 11018.9717496 , 13624.73345652, 14756.41608614,
       11108.73989181,  9260.47439818, 10064.32041784, 10538.02404346,
       10500.96292436,  7675.89349915, 16324.05968669, 19928.04054029,
       15216.64594031, 10114.24544949, 14919.62493097, 12519.42016601,
        4993.57624414, 13748.11501835,  9073.01249766, 15638.97395888,
       18011.89832693, 12548.13531076, 15493.12277077,  9823.87448933,
       16625.89146666, 13368.30877   , 13407.80319899,  8623.22907371,
       13013.8416436 , 15421.71084734, 19246.82287021, 11108.05835623,
        9092.73178759, 15055.79872868, 15765.47036618, 15160.47539017,
       18600.63754004, 12883.21600125, 10545.33980066, 14694.01584508,
       14662.85156289, 16541.6714798 , 13387.75105504, 19796.06765433,
       12861.74493701, 13118.5183051 , 16553.79800765, 12281.00301669,
       10762.95159378, 16402.38283664, 11383.18794309, 18947.44022767,
        7935.7817127 , 14326.75648281, 11427.1602887 , 10391.1426382 ,
       18924.20156158, 12303.1556165 , 19531.97852904,  8292.68214898,
       11513.46490388, 12672.18258063, 16325.07407629, 12916.14788529,
       18231.61057592, 14585.96316078,  9073.01249766, 14171.87778477,
       18375.70998972,  7174.82197238, 17637.65606148,  7095.15157883,
       11513.06037318, 16640.37962771, 20315.16254585, 16828.59474049,
       14589.07800624,  9465.95966346, 12332.97265508, 13851.35693201,
       16680.96012297,  9890.07111144,  7739.3081298 , 13255.37363838,
        7276.71664243, 21467.3018501 ,  7979.75405831, 14167.4156957 ,
       16988.68873986,  4655.71356221, 11326.01883091, 13146.90059584,
        9444.41692254, 10243.17516667, 10679.4131425 ,  9704.70966679,
       19875.0565123 , 15189.61089317, 12976.70884782,  7554.96107475,
        6441.98334547, 13913.00396081, 20460.34802593, 16468.91231276,
        6775.64511566, 16528.12603167,  6590.28367101, 13420.68293909,
        6992.24251918, 14460.90150132, 16320.19162897,  8270.45787249,
        7761.46072962,  8077.85234732, 13686.80084357,  7500.15359578,
       17835.88141868,  6869.20963891, 14672.28360351, 14996.93369132,
       21149.14263055,  8622.21468412, 12140.62830725,  9771.23914291,
       11129.87810203, 17829.24719705, 15262.03720621, 13533.95092472,
       10379.34896438, 16720.12169795, 19193.76716554, 17160.48890883,
        9402.5450328 , 10593.84591203,  4914.92024018,  8241.39404617,
       15668.45814345, 20742.65001663, 10778.5258211 , 11146.55422317,
        9579.57633065, 12607.42070636, 11433.81033787, 16958.87170128,
       11013.07491269, 14482.37256556, 17704.85124563,  9968.04557982,
       13199.62344649, 13205.43277918, 10863.07866197, 10117.02744094,
        6445.09819093,  9952.80420651, 10323.52709581, 11973.62308137,
       23731.26114069,  3883.71336032,  8129.47330415, 16130.29641856,
        8631.22636649, 13834.7683151 ,  9203.97099403, 10661.38977774,
       16725.68568084, 11447.61696334, 12168.74942065, 12547.04924449,
       13934.82370661, 14351.76275075,  9541.50082195, 19450.27935629,
       15718.73185667, 12133.71708074, 21555.30239046, 17065.57714197])

In [24]:
# Metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("mae:",mae)
print("rmse:",rmse)
print("r2:",r2)

mae: 9181.192587066631
rmse: 11453.759636393332
r2: 0.1549779076526725

# Завдання 4
Напишіть рівняння регресії за прикладом:
Ціна = 1.02*Температура - 15.6

In [26]:
# Obtain koef
m = model.coef_[0]  # Slope coefficient
b = model.intercept_  #  Free term

print(f'Рівняння регресії: Ціна = {m:.2f} * Температура + {b:.2f}')

Рівняння регресії: Ціна = 220.73 * Температура + -6131.42

# Завдання 5 (оптимально)
Перевірте як видалення викидів вплине на результат. Розгляньте один з варіантів:
* видалення викидів по стовпчику `expenses`
* видалення викидів по всіх стовпчиків

In [29]:
numeric_cols = df.select_dtypes(include=['number'])

# Q1, Q3 - квартилів і IQR for numeric
Q1 = numeric_cols.quantile(0.25)
Q3 = numeric_cols.quantile(0.75)
IQR = Q3 - Q1

# Lower and upper bound for outliners
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Outliners in nmeric columns
outliers = (numeric_cols < lower_bound) | (numeric_cols > upper_bound)

# NUmber of outliners per column
print(outliers.sum())

# Rows with outliners
df_outliers = df[outliers.any(axis=1)]
df_outliers

age           0
bmi           9
children      0
expenses    139
dtype: int64

      age   bmi  children  expenses
14     27  42.1         0  39611.76
19     30  35.3         0  36837.47
23     34  31.9         1  37701.88
29     31  36.3         2  38711.00
30     22  35.6         0  35585.58
...   ...   ...       ...       ...
1301   62  30.9         3  46718.16
1303   43  27.8         0  37829.72
1313   19  34.7         2  36397.58
1317   18  53.1         0   1163.46
1323   42  40.4         2  43896.38

[145 rows x 4 columns]

In [28]:
df_cleaned = df[~outliers.any(axis=1)]

df_cleaned.shape

(1193, 4)