<a href="https://colab.research.google.com/github/svetlanama/ai_practice/blob/dev/final_svitlana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпорт модулів

In [16]:
import pandas as pd

# Load the CSV from Google Drive
url = 'https://drive.google.com/uc?id=1lMc8CKRE3Txuk4ntqpVpzM1qTlQkYADd'
data = pd.read_csv(url)

# Display the first few rows
data.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [17]:
skills = ['Python', 'Machine Learning', 'SQL', 'Data Analysis', 'TensorFlow', 'Pandas']  # Define a skill list

def extract_skills(description):
    found_skills = [skill for skill in skills if skill.lower() in description.lower()]
    return found_skills

data['Skills'] = data['Job Description'].apply(extract_skills)
data

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Skills
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,"[Python, Machine Learning, Data Analysis]"
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,"[Python, Machine Learning]"
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,"[Python, Machine Learning, SQL, Data Analysis]"
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...","[Python, Machine Learning, Data Analysis]"
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee","[Python, Machine Learning, SQL]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini","[Python, Machine Learning, SQL, Data Analysis]"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,[Machine Learning]
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,[Machine Learning]
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),Slalom,"[Python, SQL]"
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,"[Python, Machine Learning]"

In [18]:
import re

def process_salary_range(salary_range):
    if salary_range.strip() == '-1' or salary_range.strip() == '-1.0':
        return 0, 0

    # Remove non-numeric characters except '-' for ranges
    salary_range = re.sub(r'[^\d\-\s]', '', salary_range)  # Remove $, K, and text
    # Split into low and high ranges
    low, high = salary_range.split('-')
    # Convert 'K' to thousands
    low = int(low.strip()) * 1000
    high = int(high.strip()) * 1000
    return low, high

# Example usage
# example_salary = "$95K-$160K (Glassdoor est.)"
# min_salary, max_salary = process_salary_range(example_salary)
# print(f"Min Salary: {min_salary}, Max Salary: {max_salary}")



# Apply the function to each row in the 'Salary Estimate' column
def process_salary_with_debug(salary_range):
    # print(f"Processing Salary Range: {salary_range}")  # Debug print
    return process_salary_range(salary_range)  # Call the actual function

# # # Apply the debugging function
# for _, row in data.iterrows():
#     low, high = process_salary_with_debug(row['Salary Estimate'])
#     data[['Min Salary', 'Max Salary']] = low, high

for i, row in data.iterrows():
    low, high = process_salary_with_debug(row['Salary Estimate'])
    data.loc[i, ['Min Salary', 'Max Salary']] = low, high



data

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Skills,Min Salary,Max Salary
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,"[Python, Machine Learning, Data Analysis]",53000.0,91000.0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,"[Python, Machine Learning]",63000.0,112000.0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,"[Python, Machine Learning, SQL, Data Analysis]",80000.0,90000.0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...","[Python, Machine Learning, Data Analysis]",56000.0,97000.0
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee","[Python, Machine Learning, SQL]",86000.0,143000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini","[Python, Machine Learning, SQL, Data Analysis]",72000.0,133000.0
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,[Machine Learning],56000.0,91000.0
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,[Machine Learning],95000.0,160000.0
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),Slalom,"[Python, SQL]",0.0,0.0
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,"[Python, Machine Learning]",61000.0,126000.0

In [19]:
for skill in skills:
    data[skill] = data['Skills'].apply(lambda x: 1 if skill in x else 0)

data

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Competitors,Skills,Min Salary,Max Salary,Python,Machine Learning,SQL,Data Analysis,TensorFlow,Pandas
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,-1,"[Python, Machine Learning, Data Analysis]",53000.0,91000.0,1,1,0,1,0,0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,-1,"[Python, Machine Learning]",63000.0,112000.0,1,1,0,0,0,0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,-1,"[Python, Machine Learning, SQL, Data Analysis]",80000.0,90000.0,1,1,1,1,0,0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,"Oak Ridge National Laboratory, National Renewa...","[Python, Machine Learning, Data Analysis]",56000.0,97000.0,1,1,0,1,0,0
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,"Commerce Signals, Cardlytics, Yodlee","[Python, Machine Learning, SQL]",86000.0,143000.0,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,...,"See Tickets, TicketWeb, Vendini","[Python, Machine Learning, SQL, Data Analysis]",72000.0,133000.0,1,1,1,1,0,0
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,...,-1,[Machine Learning],56000.0,91000.0,0,1,0,0,0,0
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,...,-1,[Machine Learning],95000.0,160000.0,0,1,0,0,0,0
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,...,Slalom,"[Python, SQL]",0.0,0.0,1,0,1,0,0,0
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,...,-1,"[Python, Machine Learning]",61000.0,126000.0,1,1,0,0,0,0

In [20]:
# Prepare the input (X) and output (y) as follows:

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Define features (binary skill columns) and target (Salary Estimate)
X = data[skills]
# y = data['Salary Estimate']  # Ensure this is numeric (convert if necessary)
# y = data[['Min Salary', 'Max Salary']]
y = (data['Min Salary'] + data['Max Salary']) / 2


# Normalize features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Split the data # train and test
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

X_train
X_test
y_train
y_test

342     58000.0
864    111500.0
522     25000.0
544     76500.0
682     27500.0
         ...
549    120500.0
33     114500.0
31      76500.0
713         0.0
433    154500.0
Length: 192, dtype: float64

In [21]:
# Step 2: Train the Neural Network

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


X_train.shape[1] # TODO: understand deeper
# Define the model TODO: experiment more

model = Sequential([
    # Dense(64, input_dim=12, activation='relu'),  # Input layer - skills 6 users + 6 new job
    Dense(64, input_dim=X_train.shape[1], activation='relu'),  # Input layer  # X_train.shape[1] = 6 - TODO: 6 skills
    Dense(32, activation='relu', name="dense_22"),  # Hidden layer
    Dense(1, name="dense_23")  # Output layer
])
# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])


# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2) # 100 epoch

test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

model.layers

Epoch 1/100

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 9133784064.0000 - mae: 78145.3047 - val_loss: 8458335744.0000 - val_mae: 77068.2578
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9134464000.0000 - mae: 79051.4453 - val_loss: 8458156544.0000 - val_mae: 77067.5938
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9544531968.0000 - mae: 81417.4766 - val_loss: 8457839104.0000 - val_mae: 77066.3906
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9174144000.0000 - mae: 77420.9062 - val_loss: 8457260544.0000 - val_mae: 77064.2188
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9036391424.0000 - mae: 78126.3203 - val_loss: 8456261632.0000 - val_mae: 77060.4609
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8638810112.0000 - mae: 75700.1797 - val_loss: 8454687744.0000 - val_mae: 77054.5391
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9874541568.0000 - mae: 81834.7578 - val_loss: 8452358656.0000 - val_mae: 77045.7812
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9540715520.0000 - mae: 79702.4688 - val_loss: 8449099776.0000 - val_mae: 77033.5312
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8790069248.0000 - mae: 76298.2109 - val_loss: 8444657152.0000 - val_mae: 77016.8359
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9077771264.0000 - mae: 78547.9141 - val_loss: 8438794240.0000 - val_mae: 76994.7734
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9433597952.0000 - mae: 80351.1406 - val_loss: 8431536128.0000 - val_mae: 76967.4844
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8816820224.0000 - mae: 77447.7891 - val_loss: 8422611968.0000 - val_mae: 76933.9141
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9544697856.0000 - mae: 80359.6250 - val_loss: 8411720192.0000 - val_mae: 76892.8984
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9014839296.0000 - mae: 77541.2344 - val_loss: 8398852096.0000 - val_mae: 76844.3906
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9235373056.0000 - mae: 77400.6484 - val_loss: 8383744512.0000 - val_mae: 76787.3672
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9388241920.0000 - mae: 79858.0781 - val_loss: 8366183424.0000 - val_mae: 76720.9609
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8918032384.0000 - mae: 76427.6250 - val_loss: 8347027968.0000 - val_mae: 76648.4609
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9092405248.0000 - mae: 77315.0938 - val_loss: 8325274624.0000 - val_mae: 76565.9766
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8445543424.0000 - mae: 75146.2188 - val_loss: 8301337088.0000 - val_mae: 76474.9609
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8830664704.0000 - mae: 77096.8281 - val_loss: 8274543616.0000 - val_mae: 76372.8984
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9175521280.0000 - mae: 79117.3984 - val_loss: 8244053504.0000 - val_mae: 76256.5078
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9005838336.0000 - mae: 78955.1719 - val_loss: 8212455936.0000 - val_mae: 76135.5000
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8413149184.0000 - mae: 74243.9453 - val_loss: 8177231872.0000 - val_mae: 76000.1641
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9111815168.0000 - mae: 79712.3281 - val_loss: 8138955264.0000 - val_mae: 75852.6406
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8738082816.0000 - mae: 76785.0703 - val_loss: 8097401344.0000 - val_mae: 75691.8828
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8481995264.0000 - mae: 75162.0781 - val_loss: 8051753984.0000 - val_mae: 75514.5703
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9010791424.0000 - mae: 80018.7500 - val_loss: 8004027392.0000 - val_mae: 75328.3438
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9069487104.0000 - mae: 79539.4844 - val_loss: 7953748992.0000 - val_mae: 75131.3359
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9035140096.0000 - mae: 79186.8594 - val_loss: 7901602816.0000 - val_mae: 74925.8203
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8832813056.0000 - mae: 78438.5000 - val_loss: 7844796416.0000 - val_mae: 74700.7812
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 9192140800.0000 - mae: 79471.6016 - val_loss: 7783722496.0000 - val_mae: 74457.5703
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8553681920.0000 - mae: 76149.2266 - val_loss: 7721112064.0000 - val_mae: 74206.4141
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8070531584.0000 - mae: 74492.5625 - val_loss: 7654261248.0000 - val_mae: 73936.5000
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7942898176.0000 - mae: 73045.1719 - val_loss: 7585653248.0000 - val_mae: 73657.8125
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8395594752.0000 - mae: 76370.5781 - val_loss: 7513137664.0000 - val_mae: 73360.8203
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8125105664.0000 - mae: 74138.4219 - val_loss: 7440266240.0000 - val_mae: 73060.0625
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 8349731840.0000 - mae: 76481.9531 - val_loss: 7362441728.0000 - val_mae: 72736.1953
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8147408384.0000 - mae: 75280.7969 - val_loss: 7281232896.0000 - val_mae: 72395.2812
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7996972544.0000 - mae: 74133.3438 - val_loss: 7199857152.0000 - val_mae: 72050.5156
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7932885504.0000 - mae: 75148.0391 - val_loss: 7114354176.0000 - val_mae: 71685.0469
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7647527936.0000 - mae: 72979.1484 - val_loss: 7025657344.0000 - val_mae: 71301.7500
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7688718336.0000 - mae: 72490.1328 - val_loss: 6934384640.0000 - val_mae: 70903.2188
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7340572160.0000 - mae: 72333.6016 - val_loss: 6844075008.0000 - val_mae: 70504.4219
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7752441856.0000 - mae: 73647.8516 - val_loss: 6748839424.0000 - val_mae: 70079.0078
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7048995328.0000 - mae: 70185.8125 - val_loss: 6654308864.0000 - val_mae: 69651.5391
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7470772736.0000 - mae: 72081.2891 - val_loss: 6553787392.0000 - val_mae: 69190.8047
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6910042112.0000 - mae: 68743.9375 - val_loss: 6452677120.0000 - val_mae: 68721.7344
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6770918400.0000 - mae: 69712.8828 - val_loss: 6345193984.0000 - val_mae: 68215.6172
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6878855680.0000 - mae: 69984.5234 - val_loss: 6244683264.0000 - val_mae: 67735.2578
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7203165696.0000 - mae: 71927.2109 - val_loss: 6135308800.0000 - val_mae: 67204.4688
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6784848384.0000 - mae: 70656.0234 - val_loss: 6032399360.0000 - val_mae: 66697.0703
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6587365376.0000 - mae: 68996.3125 - val_loss: 5923688448.0000 - val_mae: 66152.2969
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6085891584.0000 - mae: 65330.3633 - val_loss: 5819086848.0000 - val_mae: 65618.3750
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6375072256.0000 - mae: 68443.3203 - val_loss: 5711368192.0000 - val_mae: 65059.2539
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5825203712.0000 - mae: 64423.5430 - val_loss: 5601198080.0000 - val_mae: 64476.1094
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6144053760.0000 - mae: 65568.3984 - val_loss: 5494426112.0000 - val_mae: 63900.0000
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6079056384.0000 - mae: 67030.4375 - val_loss: 5386089984.0000 - val_mae: 63303.4062
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5943157248.0000 - mae: 65287.0625 - val_loss: 5284204544.0000 - val_mae: 62730.7852
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6338302976.0000 - mae: 68086.0469 - val_loss: 5176143872.0000 - val_mae: 62109.7578
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5705673216.0000 - mae: 64418.0469 - val_loss: 5077549568.0000 - val_mae: 61531.0078
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5335083520.0000 - mae: 62308.5703 - val_loss: 4981148672.0000 - val_mae: 60953.0117
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5407230464.0000 - mae: 63440.0781 - val_loss: 4878672384.0000 - val_mae: 60324.4961
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4941906432.0000 - mae: 59297.0586 - val_loss: 4788071936.0000 - val_mae: 59755.6914
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5156118016.0000 - mae: 61188.2539 - val_loss: 4688462336.0000 - val_mae: 59114.4961
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5206793728.0000 - mae: 61365.6523 - val_loss: 4597493248.0000 - val_mae: 58514.0195
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5491373568.0000 - mae: 63613.5742 - val_loss: 4500372480.0000 - val_mae: 57856.0078
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4799887872.0000 - mae: 59850.4336 - val_loss: 4408932352.0000 - val_mae: 57218.1953
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4653459968.0000 - mae: 58422.8906 - val_loss: 4318956544.0000 - val_mae: 56572.5117
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4834926592.0000 - mae: 59326.5391 - val_loss: 4232731136.0000 - val_mae: 55936.0000
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4619780608.0000 - mae: 58213.6406 - val_loss: 4149636608.0000 - val_mae: 55304.2617
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4273488896.0000 - mae: 55778.7188 - val_loss: 4063684864.0000 - val_mae: 54628.0703
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4191080192.0000 - mae: 54896.1250 - val_loss: 3986280704.0000 - val_mae: 54001.4102
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4580920832.0000 - mae: 56825.2188 - val_loss: 3917208832.0000 - val_mae: 53424.8906
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4542099456.0000 - mae: 56811.1562 - val_loss: 3849601280.0000 - val_mae: 52842.4883
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4413147136.0000 - mae: 56250.3984 - val_loss: 3779060992.0000 - val_mae: 52227.0273
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4165992192.0000 - mae: 54235.3242 - val_loss: 3710937088.0000 - val_mae: 51620.7070
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4284808448.0000 - mae: 54966.0195 - val_loss: 3648067072.0000 - val_mae: 51053.5352
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4197940480.0000 - mae: 54533.5859 - val_loss: 3585589248.0000 - val_mae: 50494.6289
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4132412928.0000 - mae: 54886.6016 - val_loss: 3534646016.0000 - val_mae: 50034.9609
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3887986688.0000 - mae: 52468.5625 - val_loss: 3485537536.0000 - val_mae: 49581.0508
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3821159680.0000 - mae: 52021.7266 - val_loss: 3435746560.0000 - val_mae: 49125.4570
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4218531840.0000 - mae: 53535.7305 - val_loss: 3388325632.0000 - val_mae: 48680.1016
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3560365056.0000 - mae: 50054.3789 - val_loss: 3345521664.0000 - val_mae: 48263.4492
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3807323392.0000 - mae: 51881.2852 - val_loss: 3302750976.0000 - val_mae: 47848.6289
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3833158656.0000 - mae: 51828.7852 - val_loss: 3263191552.0000 - val_mae: 47454.3203
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3486688512.0000 - mae: 48814.5820 - val_loss: 3227121664.0000 - val_mae: 47086.3672
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3725471232.0000 - mae: 51001.0820 - val_loss: 3190846464.0000 - val_mae: 46716.2305
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3882939904.0000 - mae: 51613.2539 - val_loss: 3159433984.0000 - val_mae: 46386.7422
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3599790080.0000 - mae: 49694.6328 - val_loss: 3125585408.0000 - val_mae: 46025.5977
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3754501120.0000 - mae: 50096.9570 - val_loss: 3099022336.0000 - val_mae: 45742.9688
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3474157312.0000 - mae: 48456.0078 - val_loss: 3075580416.0000 - val_mae: 45492.6641
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4026062080.0000 - mae: 51988.3125 - val_loss: 3052921600.0000 - val_mae: 45243.4297
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3820251904.0000 - mae: 51179.2969 - val_loss: 3031723776.0000 - val_mae: 45001.0430
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3302681856.0000 - mae: 46681.4414 - val_loss: 3011747840.0000 - val_mae: 44769.2266
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3391917824.0000 - mae: 46675.9570 - val_loss: 2993496576.0000 - val_mae: 44564.5547
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3570042880.0000 - mae: 49323.4414 - val_loss: 2977309440.0000 - val_mae: 44376.6758
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3745067008.0000 - mae: 49659.7461 - val_loss: 2959653376.0000 - val_mae: 44176.9297
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3676899840.0000 - mae: 49087.3477 - val_loss: 2949675008.0000 - val_mae: 44070.7578
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3473673472.0000 - mae: 47797.5039 - val_loss: 2937408000.0000 - val_mae: 43942.1758
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3392421376.0000 - mae: 48180.1562 - val_loss: 2925685248.0000 - val_mae: 43818.1094
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2811610624.0000 - mae: 41346.1641
Test Loss: 3115499776.0, Test MAE: 44913.57421875

[<Dense name=dense_1, built=True>,
 <Dense name=dense_22, built=True>,
 <Dense name=dense_23, built=True>]

In [25]:
# COSINE SIMILARITY
import numpy as np

last_6_columns = data.columns[-6:]  # Select the last 6 columns with encoded skills, TODO: adapt for more skills
user_skills = np.array([1, 1, 0, 1, 0, 1]).reshape(1, -1).astype(np.float32)

# Loop through the rows and print Job Title and the corresponding job features (last 6 columns)
for index, row in data.iterrows():
    job_title = row['Job Title']  # Extract the job title
    job_features = row[last_6_columns].values.reshape(1, -1)  # Extract the job features (last 6 columns)
    job_features_32 = row[last_6_columns].values.reshape(1, -1).astype(np.float32)  # Reshape and convert to float32

    # 1. Calculate cosine similarity between user skills and job features
    similarity = cosine_similarity(user_skills, job_features)


    # Print the results
    print(f"Job Title: {job_title}")
    print(f"Cosine Similarity: {similarity[0][0]:.2f}")
    # print(f"Predicted Fit Score: {predicted_fit[0][index]}\n")
    # print(f"Predicted Fit Score: {predicted_fit[0][0]}\n")
    # print(f"Predicted Fit Score: {predicted_fit[0][0]:.2f}\n")
    print(f"===========")

Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Healthcare Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.50
===========
Job Title: Research Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Staff Data Scientist - Technology
Cosine Similarity: 0.35
===========
Job Title: Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.67
===========
Job Title: Data Engineer I
Cosine Similarity: 0.00
===========
Job Title: Scientist I/II, Biology
Cosine Similarity: 0.00
===========
Job Title: Customer Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist - Health Data Analytics
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.67
===========
Job Title: Data Scientist
Cosine Similarity: 0.89
===========
Job Title: Senior Data Scientist / Machine Learning
Cosine Similarity: 0.50
===========
Job Title: Data Scientist - Quantitative
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Digital Health Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Scientist
Cosine Similarity: 0.67
===========
Job Title: Associate Data Analyst
Cosine Similarity: 0.50
===========
Job Title: Clinical Data Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist / Machine Learning Expert
Cosine Similarity: 0.87
===========
Job Title: Data Scientist
Cosine Similarity: 0.50
===========
Job Title: Data Scientist
Cosine Similarity: 0.50
===========
Job Title: Web Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist
Cosine Similarity: 0.67
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Engineer
Cosine Similarity: 0.35
===========
Job Title: Data Analyst
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Engineer
Cosine Similarity: 0.00
===========
Job Title: Data Scientist - Algorithms & Inference
Cosine Similarity: 0.50
===========
Job Title: Scientist
Cosine Similarity: 0.00
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Science Analyst
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.50
===========
Job Title: Lead Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Associate Data Analyst
Cosine Similarity: 0.00
===========
Job Title: Spectral Scientist/Engineer
Cosine Similarity: 0.00
===========
Job Title: College Hire - Data Scientist - Open to December 2019 Graduates
Cosine Similarity: 0.00
===========
Job Title: Data Engineer
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.89
===========
Job Title: Data Scientist, Office of Data Science
Cosine Similarity: 0.71
===========
Job Title: Data Science Analyst
Cosine Similarity: 0.50
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.82
===========
Job Title: Data Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Business Intelligence Analyst
Cosine Similarity: 0.00
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Senior Risk Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist in Artificial Intelligence Early Career
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Scientist
Cosine Similarity: 0.50
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Data Scientist - Research
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: R&D Data Analysis Scientist
Cosine Similarity: 0.00
===========
Job Title: Analytics Consultant
Cosine Similarity: 0.71
===========
Job Title: Director, Data Science
Cosine Similarity: 0.58
===========
Job Title: Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist SR
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: R&D Sr Data Scientist
Cosine Similarity: 0.29
===========
Job Title: Customer Data Scientist/Sales Engineer (Bay
Cosine Similarity: 0.58
===========
Job Title: Research Scientist
Cosine Similarity: 0.50
===========
Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Jr. Business Data Analyst
Cosine Similarity: 0.50
===========
Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Data Engineer
Cosine Similarity: 0.35
===========
Job Title: Data Analyst
Cosine Similarity: 0.00
===========
Job Title: Staff Data Scientist - Technology
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.50
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Management Specialist
Cosine Similarity: 0.35
===========
Job Title: Machine Learning Engineer
Cosine Similarity: 0.71
===========
Job Title: E-Commerce Data Analyst
Cosine Similarity: 0.00
===========
Job Title: Data Engineer Intern
Cosine Similarity: 0.35
===========
Job Title: Sr. Scientist II
Cosine Similarity: 0.00
===========
Job Title: Insurance Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist Analyst
Cosine Similarity: 0.87
===========
Job Title: Data Modeler
Cosine Similarity: 0.00
===========
Job Title: Data Analyst / Scientist
Cosine Similarity: 0.50
===========
Job Title: Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Lead Data Scientist
Cosine Similarity: 0.50
===========
Job Title: Scientist, Stem Cells and Genomics
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.35
===========
Job Title: Data Engineer
Cosine Similarity: 0.00
===========
Job Title: Data Scientist, Rice University
Cosine Similarity: 0.67
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Engineer
Cosine Similarity: 0.35
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Financial Data Analyst
Cosine Similarity: 0.00
===========
Job Title: Postdoc Scientist - T cell engineering
Cosine Similarity: 0.50
===========
Job Title: Senior Data Analyst
Cosine Similarity: 0.00
===========
Job Title: Research Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Engineer
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.67
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist
Cosine Similarity: 0.35
===========
Job Title: Data Engineer
Cosine Similarity: 0.35
===========
Job Title: Ag Data Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Engineer
Cosine Similarity: 0.00
===========
Job Title: Principal Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Platform Engineer
Cosine Similarity: 0.35
===========
Job Title: Chief Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist II
Cosine Similarity: 0.75
===========
Job Title: Senior Data Engineer
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Engineer
Cosine Similarity: 0.58
===========
Job Title: Data Engineer
Cosine Similarity: 0.58
===========
Job Title: Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Project Scientist
Cosine Similarity: 0.00
===========
Job Title: Senior Data Scientist - AI Forecasting, Finance team
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Analytics Manager
Cosine Similarity: 0.35
===========
Job Title: Senior Machine Learning (ML) Engineer / Data Scientist - Cyber Security Analytics
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Weapons and Sensors Engineer/Scientist – Entry Level
Cosine Similarity: 0.50
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Associate Scientist
Cosine Similarity: 0.00
===========
Job Title: Scientist 2, QC Viral Vector
Cosine Similarity: 0.00
===========
Job Title: Data Analyst
Cosine Similarity: 0.58
===========
Job Title: Machine Learning Engineer
Cosine Similarity: 0.50
===========
Job Title: Data Scientist/ML Engineer
Cosine Similarity: 0.58
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Customer Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Senior Scientist - Bioanalytical
Cosine Similarity: 0.50
===========
Job Title: Data Engineer
Cosine Similarity: 0.00
===========
Job Title: Data Engineer
Cosine Similarity: 0.35
===========
Job Title: Data Engineer
Cosine Similarity: 0.58
===========
Job Title: Sr. Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Scientist, Biomarker Science
Cosine Similarity: 0.71
===========
Job Title: Data Engineer 4 - Contract
Cosine Similarity: 0.50
===========
Job Title: Data Analyst - Asset Management
Cosine Similarity: 0.00
===========
Job Title: Senior Research Scientist - Embedded System Development for DevOps
Cosine Similarity: 0.50
===========
Job Title: Data Scientist - Bioinformatics
Cosine Similarity: 0.71
===========
Job Title: Data Engineer
Cosine Similarity: 0.50
===========
Job Title: Customer Data Scientist/Sales Engineer
Cosine Similarity: 0.58
===========
Job Title: Lead Data Scientist
Cosine Similarity: 0.89
===========
Job Title: Data Analyst II
Cosine Similarity: 0.00
===========
Job Title: MongoDB Data Engineer II
Cosine Similarity: 0.35
===========
Job Title: Senior Data Scientist Statistics
Cosine Similarity: 0.50
===========
Job Title: Senior Analytical Scientist
Cosine Similarity: 0.00
===========
Job Title: Senior Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Senior Spark Engineer (Data Science)
Cosine Similarity: 0.58
===========
Job Title: Data Engineer
Cosine Similarity: 0.35
===========
Job Title: BI & Platform Analytics Manager
Cosine Similarity: 0.71
===========
Job Title: Lead Data Scientist
Cosine Similarity: 0.89
===========
Job Title: Sr. Data Scientist - Analytics, Personalized Healthcare (PHC)
Cosine Similarity: 0.75
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist (Active TS SCI with Polygraph)
Cosine Similarity: 0.58
===========
Job Title: Pricipal Scientist Molecular and cellular biologist
Cosine Similarity: 0.00
===========
Job Title: Chief Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist (Actuary, FSA or ASA)
Cosine Similarity: 0.58
===========
Job Title: Staff Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Front-End, Back-End, Fullstack Developers & Data Scientist / Researchers - Cleared OR CLEARABLE (Up to 25% Profit Sharing Benefit!)
Cosine Similarity: 0.00
===========
Job Title: Senior Data Scientist / Machine Learning
Cosine Similarity: 0.50
===========
Job Title: Data Scientist - Health Data Analytics
Cosine Similarity: 0.35
===========
Job Title: Data Engineer 5 - Contract (Remote)
Cosine Similarity: 0.71
===========
Job Title: Senior Scientist - Neuroscience
Cosine Similarity: 0.71
===========
Job Title: Senior Data Analyst
Cosine Similarity: 0.58
===========
Job Title: Senior Director Biometrics and Clinical Data Management
Cosine Similarity: 0.00
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Medical Lab Scientist
Cosine Similarity: 0.00
===========
Job Title: Risk and Analytics IT, Data Scientist
Cosine Similarity: 0.35
===========
Job Title: Scientist, Analytical Development
Cosine Similarity: 0.50
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.67
===========
Job Title: Analytics Manager
Cosine Similarity: 0.00
===========
Job Title: Data Engineer
Cosine Similarity: 0.58
===========
Job Title: Digital Marketing & ECommerce Data Analyst
Cosine Similarity: 0.50
===========
Job Title: Sr. Scientist - Digital & Image Analysis/Computational Pathology
Cosine Similarity: 0.71
===========
Job Title: Senior Data Analyst
Cosine Similarity: 0.75
===========
Job Title: Principal Scientist - Immunologist
Cosine Similarity: 0.00
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.00
===========
Job Title: Principal Data Scientist with over 10 years experience
Cosine Similarity: 0.87
===========
Job Title: MED TECH/LAB SCIENTIST - LABORATORY
Cosine Similarity: 0.00
===========
Job Title: Sr. Scientist, Quantitative Translational Sciences
Cosine Similarity: 0.00
===========
Job Title: Sr. Data Scientist II
Cosine Similarity: 0.50
===========
Job Title: Excel / VBA / SQL Data Analyst
Cosine Similarity: 0.00
===========
Job Title: Machine Learning Research Scientist
Cosine Similarity: 0.87
===========
Job Title: Data Scientist
Cosine Similarity: 0.00
===========
Job Title: VP, Data Science
Cosine Similarity: 0.67
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Radar Data Analyst
Cosine Similarity: 0.71
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.50
===========
Job Title: Quality Control Scientist
Cosine Similarity: 0.00
===========
Job Title: AWS Data Engineer
Cosine Similarity: 0.50
===========
Job Title: PL Actuarial-Lead Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Deep Learning/Computer Vision Scientist
Cosine Similarity: 0.35
===========
Job Title: PV Scientist
Cosine Similarity: 0.50
===========
Job Title: Senior Data & Machine Learning Scientist
Cosine Similarity: 0.67
===========
Job Title: Principal Data Scientist (Computational Chemistry)
Cosine Similarity: 0.58
===========
Job Title: Data Engineer
Cosine Similarity: 0.00
===========
Job Title: Data Systems Specialist 2
Cosine Similarity: 0.35
===========
Job Title: Principal Scientist, Chemistry & Immunology
Cosine Similarity: 0.00
===========
Job Title: Software Engineer - Data Visualization
Cosine Similarity: 0.50
===========
Job Title: Scientist/Senior Scientist, Autoimmune
Cosine Similarity: 0.50
===========
Job Title: Data Engineer 4 - Contract (Remote)
Cosine Similarity: 0.58
===========
Job Title: UX Data Scientist (Python)
Cosine Similarity: 0.75
===========
Job Title: Staff Machine Learning Engineer
Cosine Similarity: 0.50
===========
Job Title: Principal Scientist, Hematology
Cosine Similarity: 0.00
===========
Job Title: Lead Data Engineer
Cosine Similarity: 0.58
===========
Job Title: Senior Data Engineer
Cosine Similarity: 0.35
===========
Job Title: Pharmacovigilance Scientist (Senior Pharmacovigilance)
Cosine Similarity: 0.50
===========
Job Title: Data Science Manager
Cosine Similarity: 0.71
===========
Job Title: Marketing Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Medical Laboratory Scientist
Cosine Similarity: 0.00
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.58
===========
Job Title: R&D Specialist/ Food Scientist
Cosine Similarity: 0.00
===========
Job Title: Senior Research Scientist-Machine Learning
Cosine Similarity: 0.50
===========
Job Title: Data Engineer with R
Cosine Similarity: 0.00
===========
Job Title: Analytics Manager - Data Mart
Cosine Similarity: 0.35
===========
Job Title: Sr. Data Engineer - Contract-to-Hire (Java)
Cosine Similarity: 0.35
===========
Job Title: MED TECH/LAB SCIENTIST- SOUTH COASTAL LAB
Cosine Similarity: 0.00
===========
Job Title: Food Scientist - Developer
Cosine Similarity: 0.00
===========
Job Title: Data Engineer 5 - Contract
Cosine Similarity: 0.58
===========
Job Title: Staff Scientist-Downstream Process Development
Cosine Similarity: 0.00
===========
Job Title: Sr. Data Engineer
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.71
===========
Job Title: Data Scientist - Quantitative
Cosine Similarity: 0.75
===========
Job Title: Data Scientist
Cosine Similarity: 0.75
===========
Job Title: Senior Research Statistician- Data Scientist
Cosine Similarity: 0.00
===========
Job Title: Business Data Analyst, SQL
Cosine Similarity: 0.00
===========
Job Title: Medical Technologist / Clinical Laboratory Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Senior Data Analyst
Cosine Similarity: 0.35
===========
Job Title: BI & Platform Analytics Manager
Cosine Similarity: 0.71
===========
Job Title: ATL - Data & Analytics (DA)
Cosine Similarity: 0.58
===========
Job Title: Data Engineer
Cosine Similarity: 0.35
===========
Job Title: Data Scientist
Cosine Similarity: 0.00
===========
Job Title: Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Associate Data Scientist/Computer Scientist
Cosine Similarity: 0.87
===========
Job Title: Business Intelligence Analyst / Developer
Cosine Similarity: 0.00
===========
Job Title: Lead Data Scientist
Cosine Similarity: 0.89
===========
Job Title: Sr. Data Scientist - Analytics, Personalized Healthcare (PHC)
Cosine Similarity: 0.75
===========
Job Title: Senior Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Analyst
Cosine Similarity: 0.00
===========
Job Title: Data Scientist (Active TS SCI with Polygraph)
Cosine Similarity: 0.58
===========
Job Title: Chief Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Pricipal Scientist Molecular and cellular biologist
Cosine Similarity: 0.00
===========
Job Title: Data Analyst
Cosine Similarity: 0.75
===========
Job Title: Data Analyst
Cosine Similarity: 0.35
===========
Job Title: Staff Data Scientist
Cosine Similarity: 0.58
===========
Job Title: Data Scientist (Actuary, FSA or ASA)
Cosine Similarity: 0.58
===========

In [55]:
# USE
from tensorflow.keras.layers import UnitNormalization
from tensorflow.keras.models import Model
from sklearn.metrics.pairwise import cosine_similarity

# Create a new list of layers without the last layer
new_layers = model.layers[:-1]  # Exclude the last layer

# Build a new model using the new layers
model_output = Sequential(new_layers)
# print("Original2 model layers:", new_model.layers)
model_output.add(UnitNormalization())


# Передбачення особливостей вакансій через модель
# X = data[skills]
X_features = model_output.predict(X)
# Передбачення особливостей користувача
predicted_fit = model_output.predict(user_skills)
print(f"predicted_fit.shape: {predicted_fit.shape} ") # (1, 32)



scores = X_features @ predicted_fit.T
print(f"Розрахунок оцінок схожості: {scores.shape}") # (кількість вакансій, 1)


# Вивести топ-5 вакансій
print("Top 5 job recommendations for the user:")
for rank, index in enumerate(top_indices, start=1):
    job_title = data['Job Title'].iloc[index]  # Назва вакансії
    # fit_score = job_fit_scores[index]  # Значення схожості
    fit_score = scores[index, 0]
    print(f"{rank}. {job_title} - Fit Score: {fit_score:.2f}")



# for index, row in data.iterrows():
#     job_title = row['Job Title']  # Extract the job title
#     job_features = row[last_6_columns].values.reshape(1, -1)  # Extract the job features (last 6 columns)
#     #job_features_32 = row[last_6_columns].values.reshape(1, -1).astype(np.float32)  # Reshape and convert to float32

#     # Ensure that the index does not go out of bounds
#     if index < len(predicted_fit[0]):
#         print(f"Predicted Fit Score for {job_title}: skills: job_features:{job_features} score: {predicted_fit[0][index]:.2f}")
#     else:
#         print(f"Index {index} is out of bounds for predicted_fit.")

#     # print(f"Predicted Fit Score: {predicted_fit[0][index]}\n")

30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step
predicted_fit.shape: (1, 32)
Розрахунок оцінок схожості: (956, 1)
Top 5 job recommendations for the user:
1. Healthcare Data Scientist - Fit Score: 1.00
2. Data Scientist - Fit Score: 1.00
3. Customer Data Scientist - Fit Score: 1.00
4. Data Scientist - Fit Score: 1.00
5. Data Scientist - Fit Score: 1.00

In [ ]:
 ###### End #######

# Завдання 6
Збережіть нейромережу та зробіть прогноз